增加自動存入綠寶石+一些指令
SiongSng/Better-MCFallout-Bot pull request #24
Opened 2023-06-01 13:06 UTC by Dasupergrasskakjd

2023-06-07 01:13 UTC, SiongSng requested changes
非常感謝您的貢獻，我先初步做一些 code review，如果有任何問題，歡迎直接問我！

2023-06-07 01:13 UTC, SiongSng commented on app/lib/src/config/config_storage.dart
> +  set hideWarn(bool value) => ConfigHelper.set<bool>('hide_warn', value);
建議將隱藏警告與隱藏生命值分開為兩個值

2023-06-07 01:13 UTC, SiongSng commented on .github/ISSUE_TEMPLATE/bug_report.md
> +name: Bug report
應該不必加入這個問題模板，考慮大多數使用者都在 Discord 回報。
若要加入，應於另個 PR 處理，避免與存綠功能衝突。

2023-06-07 01:13 UTC, SiongSng commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: Feature request
功能請求的模板也是
若要加入，應於另個 PR 處理，避免與存綠功能衝突。

2023-06-07 01:13 UTC, SiongSng commented on .github/workflows/release.yml
> +permissions:
請問加入權限選項的用途是什麼？感謝。

2023-06-07 06:22 UTC, Dasupergrasskakjd commented on .github/workflows/release.yml
> +permissions:
不加入的話release_file不會成功運行

2023-06-07 06:24 UTC, Dasupergrasskakjd commented on app/lib/src/config/config_storage.dart
> +  set hideWarn(bool value) => ConfigHelper.set<bool>('hide_warn', value);
額這個是原本應該移除了的
某次切換branch的時候不知道爲什麽有回來了

2023-06-07 06:25 UTC, Dasupergrasskakjd commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: Feature request
ok那我移除

2023-06-07 06:36 UTC, Dasupergrasskakjd commented on app/lib/src/config/config_storage.dart
> +  set hideWarn(bool value) => ConfigHelper.set<bool>('hide_warn', value);
hide health 也應該是移除這個設定一定會隱藏

2023-06-08 13:50 UTC, SiongSng commented on app/lib/src/config/config_storage.dart
> +  set hideWarn(bool value) => ConfigHelper.set<bool>('hide_warn', value);
因為有的玩家說想要看到生命值顯示才能了解有沒有正常打怪，所以沒有設計成一定隱藏生命值的訊息。

2023-06-09 19:48 UTC, Dasupergrasskakjd commented on app/lib/src/config/config_storage.dart
> +  set hideWarn(bool value) => ConfigHelper.set<bool>('hide_warn', value);
好的 回復了

2023-06-10 02:21 UTC, SiongSng commented on .github/workflows/release.yml
> +permissions:
可以麻煩您 revert 這個檔案的變更嗎？
如果你是為了要取得編譯後的檔案，每次 commit 的時候 GitHub Action 都會自動編譯一份檔案，不必執行 Release。

2023-06-10 02:29 UTC, SiongSng requested changes

2023-06-10 02:29 UTC, SiongSng commented on app/lib/src/config/config_storage.dart
> +        //'hide_health': hideHealth,
```suggestion
        'hide_health': hideHealth,
```

2023-06-10 02:29 UTC, SiongSng commented on app/lib/src/pages/bot_status_page.dart
> +                      if (commandController.text == ".leave" || commandController.text == ".quit"){
如果要離開伺服器 UI 上有按鈕，應該不必特別新增指令？

2023-06-10 02:35 UTC, SiongSng requested changes

2023-06-10 02:35 UTC, SiongSng commented on core/src/util/action_handler.ts
> +            /*一次攻擊太多實體會被踢 所以取消自動暴擊
麻煩把 debug 用的程式碼刪除，感謝。

2023-06-10 02:35 UTC, SiongSng commented on app/pubspec.yaml
> +version: 1.1.0
PR 不需包含版本變更

2023-06-10 02:35 UTC, SiongSng commented on app/lib/src/pages/settings_page.dart
> +              message: '自動存入綠寶石',
```suggestion
              message: '自動存入身上的綠寶石',
```

2023-06-10 02:35 UTC, SiongSng commented on app/lib/src/pages/bot_status_page.dart
> +                                '自動使用/bank存入綠寶石',
```suggestion
                                '自動存入身上的綠寶石',
```

2023-06-10 02:35 UTC, SiongSng commented on app/lib/src/pages/bot_status_page.dart
> +                                title: const Text('自動存入')),
這樣描述可能會更完整？

```suggestion
                                title: const Text('自動存綠')),
```

2023-06-11 12:20 UTC, Dasupergrasskakjd commented on .github/workflows/release.yml
> +permissions:
ok

2023-06-12 09:11 UTC, SiongSng commented on .github/workflows/release.yml
> +permissions:
感謝

2025-05-15 19:49 UTC, closed without merging